CREATE TABLE Users (
    UserID NVARCHAR(100) PRIMARY KEY,
    Email NVARCHAR(255) NOT NULL,
    DisplayName NVARCHAR(100) NOT NULL,
    CreatedDate DATETIME DEFAULT GETDATE()
);

CREATE TABLE Events (
    EventID INT IDENTITY(1,1) PRIMARY KEY,
    UserID NVARCHAR(100) NOT NULL,
    Title NVARCHAR(255) NOT NULL,
    StartDate DATETIME NOT NULL,
    EndDate DATETIME NULL,
    Description NVARCHAR(MAX) NULL,
    CreatedDate DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (UserID) REFERENCES Users(UserID)
);

CREATE TABLE Notes (
    NoteID INT IDENTITY(1,1) PRIMARY KEY,
    EventID INT NOT NULL,
    Content NVARCHAR(MAX) NOT NULL,
    CreatedDate DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (EventID) REFERENCES Events(EventID) ON DELETE CASCADE
);

CREATE TABLE FileAttachments (
    FileID INT IDENTITY(1,1) PRIMARY KEY,
    EventID INT NOT NULL,
    FileName NVARCHAR(255) NOT NULL,
    BlobPath NVARCHAR(255) NOT NULL,
    FileSize INT NULL,
    ContentType NVARCHAR(100) NULL,
    UploadDate DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (EventID) REFERENCES Events(EventID) ON DELETE CASCADE
);

CREATE TABLE Reminders (
    ReminderID INT IDENTITY(1,1) PRIMARY KEY,
    EventID INT NOT NULL,
    UserID NVARCHAR(100) NOT NULL,
    ReminderTime DATETIME NOT NULL,
    NotificationMethod NVARCHAR(50) NOT NULL,
    Processed BIT DEFAULT 0,
    CreatedDate DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (EventID) REFERENCES Events(EventID) ON DELETE CASCADE,
    FOREIGN KEY (UserID) REFERENCES Users(UserID)
);